import Header from "@/components/layouts/dashboard/Header";
import Sidebar from "@/components/layouts/dashboard/Sidebar";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Dashboard | Job Portal",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <main className="flex flex-row bg-background w-svw">
      <section id="sidebar" className="min-h-svh w-1/5">
        <Sidebar />
      </section>
      <div className="w-4/5">
        <section id="header">
          <Header />
        </section>
        <section id="content">{children}</section>
      </div>
    </main>
  );
}
